version: '3.7'

services:
  worker-ai-lip-sync:
    image: ai-lip-sync
    container_name: worker-ai-lip-sync
    volumes:
      - .:/app
      - ./scripts/wav2lip/checkpoints:/app/scripts/wav2lip/checkpoints
      - ./scripts/wav2lip/face_detection/detection/sfd:/app/scripts/wav2lip/face_detection/detection/sfd
      - ./scripts/wav2lip/predicator:/app/scripts/wav2lip/predicator
      - ./modules/degradations.py:/usr/local/lib/python3.11/site-packages/basicsr/data/degradations.py
      - app-public-volume-v2:/app/static/public
    command: bash -c "celery -A ai_celery.router worker -Q ai_lip_sync --loglevel=info --pool=gevent --concurrency=1 -E --logfile=logs/celery.log --hostname=celery@ai_lip_sync && tail -f /dev/null" &
#    restart: always
    networks:
      - aiservice-net-dev-v2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
      # limits:
      #   cpus: '0.50'
      #   memory: 2G

volumes:
  "app-public-volume-v2":
    external: true

networks:
  aiservice-net-dev-v2:
    external: true